dist: bionic
os: linux
language:
  - c
  - cpp
compiler:
  - gcc

addons:
  apt:
    packages:
      - cmake

before_install:
  # Install valid arm-none-eabi-gcc compiler
  - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo apt-get -q update
  - sudo apt install gcc-arm-embedded -y

before_script:
  # Show current versions
  - gcc --version
  - g++ --version
  - cmake --version
  - arm-none-eabi-gcc --version

jobs:
  include:
    - stage: Crosscompile Build
      script:
        # Download tivaware library
        - git clone https://github.com/caiotoledo/ti-tivaware.git ~/tiva-c/
        # Run cmake
        - cmake -DLOG_LEVEL=LOG_DEBUG_INFO -DCMAKE_TOOLCHAIN_FILE=$(realpath ./etc/toolchain_tivaware.cmake) -DTIVAWARE_PATH=$(realpath ~/tiva-c) .
        - cmake -DLOG_LEVEL=LOG_DEBUG_INFO -DCMAKE_TOOLCHAIN_FILE=$(realpath ./etc/toolchain_tivaware.cmake) -DTIVAWARE_PATH=$(realpath ~/tiva-c) .
        # build project
        - make
    - stage: Unittest
      script:
        # Install GTest and GMock
        - git clone --branch release-1.8.1 https://github.com/google/googletest.git
        - cd googletest
        - cmake -DBUILD_SHARED_LIBS=ON .
        - make
        - sudo cp -a googletest/include/gtest /usr/include
        - sudo cp -a googlemock/include/gmock /usr/include
        - find . -iname "*.so" | xargs -I{} sudo cp -av {} /usr/lib/
        - cd ../
        # Run cmake
        - cmake .
        # build unittest
        - make
        # Run tests
        - make test
